version: "3.7"
services:

  fast_zero:
    container_name: fast_zero
    image: fast_zero
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    command: poetry run uvicorn app.app:app --host='0.0.0.0'